// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vj0emktZzie767UyuIwls9MLJBohOpY',
    appId: '1:1077831417382:web:da0644a87c17734ad2b0e7',
    messagingSenderId: '1077831417382',
    projectId: 'khata-4ffe4',
    authDomain: 'khata-4ffe4.firebaseapp.com',
    storageBucket: 'khata-4ffe4.firebasestorage.app',
    measurementId: 'G-3B8FHCTSYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdp_MXG2xWmROBxznhZLDFa2Fz990wt_s',
    appId: '1:1077831417382:android:e1e0780bf16584edd2b0e7',
    messagingSenderId: '1077831417382',
    projectId: 'khata-4ffe4',
    storageBucket: 'khata-4ffe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEU5mnPbEv1Tg5tjuG4AzlvxfAUpFpRj0',
    appId: '1:1077831417382:ios:66926dc37d352dabd2b0e7',
    messagingSenderId: '1077831417382',
    projectId: 'khata-4ffe4',
    storageBucket: 'khata-4ffe4.firebasestorage.app',
    iosBundleId: 'com.example.khataboook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEU5mnPbEv1Tg5tjuG4AzlvxfAUpFpRj0',
    appId: '1:1077831417382:ios:66926dc37d352dabd2b0e7',
    messagingSenderId: '1077831417382',
    projectId: 'khata-4ffe4',
    storageBucket: 'khata-4ffe4.firebasestorage.app',
    iosBundleId: 'com.example.khataboook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vj0emktZzie767UyuIwls9MLJBohOpY',
    appId: '1:1077831417382:web:5bbaa1990f66f4c7d2b0e7',
    messagingSenderId: '1077831417382',
    projectId: 'khata-4ffe4',
    authDomain: 'khata-4ffe4.firebaseapp.com',
    storageBucket: 'khata-4ffe4.firebasestorage.app',
    measurementId: 'G-H8DH9SC8LR',
  );
}
